**By:** *Ahmed Sharaf* & *Mina Sameh*

In this notebook you will practice how to:
1. Calculate the determinant of a 2x2 matrix with and without using numpy.linalg
2. Calculate the determinant of a 3x3 matrix with and without using numpy.linalg
3. Calculate the inverse of a 2x2 matrix using numpy.linalg
4. Calculate the inverse of a 3x3 matrix using numpy.linalg
5. Finding the rank of a matrix using numpy

### Notice

**Please Note:**  
When writing code, make sure to place it in the designated area marked with `# code here`.  
If there is a `pass` keyword in the code, please remove it and replace it with the required code.

# Calculating the determinant using numpy.linalg

In [1]:
import numpy as np

In [2]:
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [3]:
a3 = np.array([[1,1,2],[2,3,1],[3,4,-5]])
print(a3)

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]


In [4]:
## Determinate of a2, a3
a2_det=np.linalg.det(a2)
a3_det=np.linalg.det(a3)

print('determinant of a2 is:\n' , round(a2_det) ,'\ndeterminant of a3 is:\n' , round(a3_det))

determinant of a2 is:
 -2 
determinant of a3 is:
 -8


# Calculating the determinant of a 2x2 matrixwithout using numpy

In [5]:
def Det2(mat):
    det= (mat[0][0]*mat[1][1]) -(mat[0][1]*mat[1][0])
    return det

print(Det2(a2))

-2


# Calculating the determinant of a 3x3 matrix without using numpy

One idea
1. write a function to calculate the minor matrices. (hint, use slices)
2. write a function to calculate the cofactors (this should call the first function, and the determinant function)
3. the determinant function calls the function in step two and adds the results together.

Another idea
use recursion ==> code credit https://stackoverflow.com/questions/3819500/code-to-solve-determinant-using-python-without-using-scipy-linalg-det

In [6]:
# delete function removes a sub-array from the input array
# first argument is the original array
# second argument is the index to the sub-array to be removed
# third argument is the axis among which the deletion happens (0: x axis "row" and 1: y axis "column")
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# print(arr)


def sub_det(matrix,i):
    mat2=np.delete(matrix,0,0)
    mat3=np.delete(mat2,i,1)
    point = matrix[0][i]
    if (i%2 != 0 ):point=-point
    return point*(mat3[0][0]*mat3[1][1]-mat3[0][1]*mat3[1][0])

def det_3x3(array):
    result=0
    for i in range(3):
        sub_result=sub_det(array,i)
        result+=sub_result
        
    return result
    


det_3x3(a3)

-8

In [8]:
def minor(arr,i,j):
    ## Code Here
    pass

def det(arr):
    ## Code Here
    pass

# print(a3)
# det(a3)


# عملتها فوق ماخدتش بالي من ده

# Calculating the inverse using numpy.linalg

In [9]:
# The inverse of 2 x 2 matrix

a2 = np.array([[1,2],[3,4]])

print(a2)

np.linalg.inv(a2)

# Code Here

[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
# The inverse of a singular matrix

a3 = np.array([[1,2],[2,4]])

print(a3)

## Code Here
np.linalg.inv(a3)

#obviously det is equal to zero
#1*4-2*2=0

[[1 2]
 [2 4]]


LinAlgError: Singular matrix

In [11]:
# The inverse of 3 x 3 matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Calculating the inverse of the matrix
## Code Here
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [12]:
# Inverses of several matrices can
# be computed at once

A = np.array([[[1., 2.],
               [3., 4.]],
              [[1, 3],
               [3, 5]]])


# Calculating the inverse of the matrix
## Code Here

np.linalg.inv(A)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])

# Calculating the inverse of a 2x2 matrix without using numpy

1. Code a function to calculate the determinant of 2x2 matrix
2. Code a function that interchange the diagonal elements of a 2x2 matrix and inverse the sign of the off diagonal elements
3. Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists

In [13]:
#step -1- we already coded the det function that works for 2x2 and nxn size matrix

#step -2-
def interchangeMatrix(A):
    B=np.array([[A[1][1],-A[0][1]],[-A[1][0] , A[0][0]]])
    return B

#step -3-
def inverse2x2(A):
    det = Det2(A)
    changed= interchangeMatrix(A)
    inverse = (1/det) * changed
    return inverse

a2 = np.array([[1,2],[3,4]])
print(inverse2x2(a2))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Calculating the inverse of a 3x3 matrix without using numpy

# Use the adjoint matrix method

Coding a Python code to inverse a 3x3 matrix (no numpy.linalg.inv allowed):
1. Coding a function that checks if a 3x3 matrix is invertible
2. Coding a function that generates the transpose of a 3x3 matrix
3. Coding a function that generates the matrix of minors of a 3x3 matrix
4. Coding a function that generates the matrix of cofactors of a 3x3 matrix
5. Coding a function that generates the inverse of a 3x3 matrix if it exists


In [14]:
#step -1- a matrix is invertible only if its determinant != 0
def invertible(A):
    det = det_3x3(A)
    if det == 0:
        return False
    else :return True

#step -2- rows and columns could be interchanged without the need of built-in methods
def transposeM(A):
    A[0][1], A[1][0] = A[1][0] , A[0][1]
    A[0][2], A[2][0] = A[2][0] , A[0][2]
    A[1][2], A[2][1] = A[2][1] , A[1][2]
    return A
    
    

#step -3- we coded that previously minor(arr,i,j)
def minor(arr, i,j):
    mat2=np.delete(arr,i,0)
    mat3=np.delete(mat2,j,1)
    return (mat3[0][0]*mat3[1][1]-mat3[0][1]*mat3[1][0])

    
#step -4- Calculating the matrix of cofactors (minors determinants multiplied by signs)
def cofactors(A):
    cofactored =np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            cofactored[i][j]=minor(A,i,j)
            if abs(i-j) == 1: cofactored[i][j]= -cofactored[i][j]
            
            
            
    return cofactored


#step -5- Inverse is the transpose of the cofactor matrix divided by the determinant of the original/input matrix
def inverse3x3(A):
    if invertible(A) == False:
        raise ValueError('the matrix is singular, dont have an inverse because the determinant is equal to ZERO')
    det = det_3x3(A)
    B = cofactors(A)
    C = transposeM(B)
    inverse = (1/det) * C
    return inverse
    


B = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(inverse3x3(B))

#[ 0.17647059 -0.00326797 -0.02287582]
# [ 0.05882353 -0.13071895  0.08496732]
# [-0.11764706  0.1503268   0.05228758]]
#check
print(np.linalg.inv(B))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [15]:
### testing if the det is equal to zero case
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
inverse3x3(matrix)

ValueError: the matrix is singular, dont have an inverse because the determinant is equal to ZERO

# Finding the rank of a matrix using numpy

In [16]:
a3 = np.array([[1,2],[2,4]])

np.linalg.matrix_rank(a3)

1